---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  generateName: keycloak-
  annotations:
    olm.providedAPIs: 'Keycloak.v2alpha1.k8s.keycloak.org,KeycloakRealmImport.v2alpha1.k8s.keycloak.org'
  namespace: keycloak
spec:
  targetNamespaces:
    - keycloak
  upgradeStrategy: Default
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/rhbk-operator.keycloak: ''
  name: rhbk-operator
  namespace: keycloak
spec:
  channel: stable-v22
  installPlanApproval: Automatic
  name: rhbk-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: rhbk-operator.v22.0.8-opr.2
